import type { PresetDefinition } from './types';

const upstream = 'https://github.com/MelodicBloom/shader-gallery/tree/main/abalone';
const shader = '/shaders/abalone.frag';

export const presets: PresetDefinition[] = [
  { id:'thin-film-01', family:'thin-film', title:'Thin Film Alpha', description:'Angle-shifting interference with restrained spectral rings.', glslPath:shader, tier:'free', tags:['interference','iridescence','surface'], semanticRole:'discovery through changing perspective', emotionalGradient:['curiosity','clarity'], motionToken:'motion.discovery.drift', sourceGalleryRef:upstream, uniformsDefault:{speed:.16,intensity:.9,scale:1.05,family:0,structure:.22,spectral:1,edge:.7,flow:.45,depth:.35}},
  { id:'shell-01', family:'shell', title:'Abalone Shell', description:'Layered nacre shimmer with organic depth and pearl-like highlights.', glslPath:shader, tier:'free', tags:['nacre','organic','pearl'], semanticRole:'material coherence emerging from layered variation', emotionalGradient:['wonder','confidence'], motionToken:'motion.transition.bloom', sourceGalleryRef:upstream, uniformsDefault:{speed:.1,intensity:.82,scale:1.35,family:1,structure:.88,spectral:.72,edge:.28,flow:.72,depth:.9}},
  { id:'aurora-01', family:'aurora', title:'Aurora Veil', description:'A cool-spectrum atmospheric field with flowing luminous curtains.', glslPath:shader, tier:'free', tags:['ambient','veil','atmosphere'], semanticRole:'orientation and environmental tone', emotionalGradient:['distance','invitation'], motionToken:'motion.discovery.orbit', sourceGalleryRef:upstream, uniformsDefault:{speed:.065,intensity:.72,scale:.7,family:2,structure:.34,spectral:.86,edge:.18,flow:1,depth:.55}},
  { id:'fresnel-01', family:'fresnel', title:'Fresnel Halo', description:'Dark optical volume with a responsive, angle-dependent luminous rim.', glslPath:shader, tier:'free', tags:['edge','halo','reflectance'], semanticRole:'focus through boundary emphasis', emotionalGradient:['diffusion','attention'], motionToken:'motion.focus.resonate', sourceGalleryRef:upstream, uniformsDefault:{speed:.12,intensity:.9,scale:.92,family:3,structure:.18,spectral:.48,edge:1,flow:.32,depth:.82}},
  { id:'holographic-01', family:'holographic', title:'Holographic Lattice', description:'Fine diffraction grid with spectral scanning and foil-like shimmer.', glslPath:shader, tier:'free', tags:['foil','diffraction','lattice'], semanticRole:'continuity through structured variation', emotionalGradient:['fragmentation','coherence'], motionToken:'motion.structure.tessellate', sourceGalleryRef:upstream, uniformsDefault:{speed:.14,intensity:.82,scale:1.15,family:4,structure:1,spectral:1,edge:.45,flow:.58,depth:.4}},
  { id:'liquid-metal-01', family:'liquid-metal', title:'Mercury Current', description:'Reflective liquid-metal folds with slow pressure-driven circulation.', glslPath:shader, tier:'free', tags:['metal','viscous','reflective'], semanticRole:'active processing and energetic transfer', emotionalGradient:['pressure','release'], motionToken:'motion.processing.current', sourceGalleryRef:upstream, uniformsDefault:{speed:.09,intensity:.86,scale:1.1,family:5,structure:.64,spectral:.32,edge:.66,flow:.9,depth:1}},
  { id:'velvet-01', family:'velvet', title:'Velvet Signal', description:'Soft directional fibers with grazing-light compression and bloom.', glslPath:shader, tier:'free', tags:['fiber','soft','grazing-light'], semanticRole:'listening, waiting, and receptive state', emotionalGradient:['quiet','readiness'], motionToken:'motion.listening.breathe', sourceGalleryRef:upstream, uniformsDefault:{speed:.055,intensity:.78,scale:1.2,family:6,structure:.78,spectral:.44,edge:.2,flow:.28,depth:.68}},
  { id:'crystal-01', family:'crystal', title:'Prismatic Crystal', description:'Faceted translucent geometry with refracted spectral seams.', glslPath:shader, tier:'free', tags:['facet','refraction','prism'], semanticRole:'decision points and resolved structure', emotionalGradient:['ambiguity','resolution'], motionToken:'motion.resolve.crystallize', sourceGalleryRef:upstream, uniformsDefault:{speed:.08,intensity:.88,scale:1,family:7,structure:.92,spectral:.92,edge:.72,flow:.18,depth:.86}},
  { id:'plasma-01', family:'plasma', title:'Ion Bloom', description:'Electric plasma filaments that gather, fork, and discharge with vivid chroma.', glslPath:shader, tier:'free', tags:['electric','plasma','charge'], semanticRole:'activation and immediate feedback', emotionalGradient:['potential','release'], motionToken:'motion.activate.ionize', sourceGalleryRef:upstream, uniformsDefault:{speed:.13,intensity:.92,scale:1.05,family:8,structure:.74,spectral:1,edge:.86,flow:1,depth:.72}},
  { id:'opal-glass-01', family:'opal-glass', title:'Opal Glass', description:'Milky translucent depth with slow internal color migration and soft caustics.', glslPath:shader, tier:'free', tags:['glass','opal','caustic'], semanticRole:'containment with visible internal state', emotionalGradient:['opacity','revelation'], motionToken:'motion.state.refract', sourceGalleryRef:upstream, uniformsDefault:{speed:.07,intensity:.86,scale:.95,family:9,structure:.38,spectral:.78,edge:.42,flow:.48,depth:.92}},
  { id:'magnetic-ink-01', family:'magnetic-ink', title:'Magnetic Ink', description:'Dense pigment lines align and relax around an invisible moving field.', glslPath:shader, tier:'free', tags:['ink','field','alignment'], semanticRole:'sorting, filtering, and directed attention', emotionalGradient:['scatter','alignment'], motionToken:'motion.filter.align', sourceGalleryRef:upstream, uniformsDefault:{speed:.1,intensity:.84,scale:1.15,family:10,structure:1,spectral:.35,edge:.58,flow:.72,depth:.78}},
  { id:'electric-mesh-01', family:'electric-mesh', title:'Electric Mesh', description:'A luminous responsive network with pulsing junctions and travelling current.', glslPath:shader, tier:'free', tags:['network','pulse','current'], semanticRole:'connectivity and system readiness', emotionalGradient:['isolation','synchrony'], motionToken:'motion.network.propagate', sourceGalleryRef:upstream, uniformsDefault:{speed:.12,intensity:.9,scale:1.1,family:11,structure:.92,spectral:.94,edge:.74,flow:.88,depth:.64}}
];

export const families = ['all', ...Array.from(new Set(presets.map((preset) => preset.family)))] as const;
