import type { PresetDefinition } from './types';

const upstream = 'https://github.com/MelodicBloom/shader-gallery/tree/main/abalone';
const shader = '/shaders/abalone.frag';
const u = (family:number,speed:number,intensity:number,scale:number,structure:number,spectral:number,edge:number,flow:number,depth:number) => ({ family,speed,intensity,scale,structure,spectral,edge,flow,depth });

export const presets: PresetDefinition[] = [
  { id:'thin-film-01', family:'thin-film', title:'Thin Film Interference', description:'Layered interference membranes with drifting spectral caustics rather than flat radial bands.', glslPath:shader, tier:'free', tags:['interference','membrane','iridescence'], semanticRole:'discovery through changing perspective', emotionalGradient:['curiosity','clarity'], motionToken:'motion.discovery.refract', sourceGalleryRef:upstream, uniformsDefault:u(0,.22,.92,.94,.36,1,.76,.8,.52) },
  { id:'shell-01', family:'shell', title:'Abalone Shell', description:'Layered nacre shimmer with organic ridges, pearl depth, and migrating highlights.', glslPath:shader, tier:'free', tags:['nacre','organic','pearl'], semanticRole:'material coherence emerging from layered variation', emotionalGradient:['wonder','confidence'], motionToken:'motion.transition.bloom', sourceGalleryRef:upstream, uniformsDefault:u(1,.12,.84,1.28,.9,.78,.34,.78,.94) },
  { id:'aurora-01', family:'aurora', title:'Aurora Veil', description:'A cool-spectrum atmospheric field with flowing luminous curtains.', glslPath:shader, tier:'free', tags:['ambient','veil','atmosphere'], semanticRole:'orientation and environmental tone', emotionalGradient:['distance','invitation'], motionToken:'motion.discovery.orbit', sourceGalleryRef:upstream, uniformsDefault:u(2,.1,.76,.72,.38,.9,.2,1,.6) },
  { id:'fresnel-01', family:'fresnel', title:'Fresnel Aperture', description:'A breathing optical aperture with 3D tilt, parallax, lens depth, and a moving luminous rim.', glslPath:shader, tier:'free', tags:['aperture','parallax','reflectance'], semanticRole:'focus through boundary emphasis', emotionalGradient:['diffusion','attention'], motionToken:'motion.focus.aperture', sourceGalleryRef:upstream, uniformsDefault:u(3,.18,.94,.9,.34,.72,1,.78,1) },
  { id:'holographic-01', family:'holographic', title:'Holographic Moiré Field', description:'Layered diffraction lattices, moving moiré interference, and spectral scan currents.', glslPath:shader, tier:'free', tags:['moire','diffraction','lattice'], semanticRole:'continuity through structured variation', emotionalGradient:['fragmentation','coherence'], motionToken:'motion.structure.interfere', sourceGalleryRef:upstream, uniformsDefault:u(4,.28,.9,1.08,1,1,.58,1,.56) },
  { id:'liquid-metal-01', family:'liquid-metal', title:'Mercury Current', description:'Reflective liquid-metal folds with slow pressure-driven circulation.', glslPath:shader, tier:'free', tags:['metal','viscous','reflective'], semanticRole:'active processing and energetic transfer', emotionalGradient:['pressure','release'], motionToken:'motion.processing.current', sourceGalleryRef:upstream, uniformsDefault:u(5,.11,.88,1.06,.68,.38,.72,.94,1) },
  { id:'velvet-01', family:'velvet', title:'Velvet Datamosh', description:'Directional velvet fibers interrupted by controlled chromatic displacement and packet-loss blooms.', glslPath:shader, tier:'free', tags:['fiber','datamosh','glitch'], semanticRole:'listening under imperfect transmission', emotionalGradient:['quiet','signal'], motionToken:'motion.listening.datamosh', sourceGalleryRef:upstream, uniformsDefault:u(6,.2,.84,1.16,.92,.7,.32,.72,.76) },
  { id:'crystal-01', family:'crystal', title:'Kinetic Prismatic Crystal', description:'Rotating Voronoi facets with animated refraction, spectral seams, and crystalline parallax.', glslPath:shader, tier:'free', tags:['voronoi','refraction','prism'], semanticRole:'decision points and resolved structure', emotionalGradient:['ambiguity','resolution'], motionToken:'motion.resolve.crystallize', sourceGalleryRef:upstream, uniformsDefault:u(7,.24,.94,.94,1,.98,.82,.74,.94) },
  { id:'ion-bloom-01', family:'ion-bloom', title:'Ion Bloom', description:'Electric branching discharge with plasma bloom and luminous field collapse.', glslPath:shader, tier:'free', tags:['plasma','branching','electric'], semanticRole:'activation and energetic emergence', emotionalGradient:['charge','release'], motionToken:'motion.activate.discharge', sourceGalleryRef:upstream, uniformsDefault:u(8,.2,.98,.96,.72,1,.88,1,.74) },
  { id:'opal-glass-02', family:'opal-glass', title:'Opaline Caustic Vessel', description:'Deep translucent opal with lensing, caustic ribbons, internal bubbles, and spectral subsurface glow.', glslPath:shader, tier:'free', tags:['caustic','translucent','subsurface'], semanticRole:'soft containment and refracted depth', emotionalGradient:['opacity','revelation'], motionToken:'motion.surface.caustic', sourceGalleryRef:upstream, uniformsDefault:u(9,.15,.9,.92,.58,.92,.62,.84,1) },
  { id:'magnetic-ink-01', family:'magnetic-ink', title:'Magnetic Ink', description:'Pigment filaments align around a moving dipole field and reorganize under pressure.', glslPath:shader, tier:'free', tags:['ferrofluid','field','filament'], semanticRole:'alignment under invisible influence', emotionalGradient:['scatter','orientation'], motionToken:'motion.field.align', sourceGalleryRef:upstream, uniformsDefault:u(10,.16,.92,1.02,.94,.72,.5,.92,.88) },
  { id:'electric-mesh-02', family:'electric-mesh', title:'Electric Mesh Accelerator', description:'Fast travelling currents pulse through an elastic node lattice with junction flares and wave propagation.', glslPath:shader, tier:'free', tags:['network','current','wave'], semanticRole:'distributed transmission and coordinated activation', emotionalGradient:['potential','propagation'], motionToken:'motion.network.surge', sourceGalleryRef:upstream, uniformsDefault:u(11,.62,1,1.04,.9,1,.9,1,.68) },
  { id:'quantum-knot-01', family:'quantum-knot', title:'Quantum Knot', description:'A projected torus-knot probability filament with phase precession and interference halos.', glslPath:shader, tier:'free', tags:['torus-knot','phase','topology'], semanticRole:'entangled continuity across apparent crossings', emotionalGradient:['entanglement','continuity'], motionToken:'motion.quantum.precess', sourceGalleryRef:upstream, uniformsDefault:u(12,.25,.96,.88,.76,1,.74,.84,.92) },
  { id:'wave-function-01', family:'wave-function', title:'Wave Function Collapse', description:'Complex-valued orbital lobes, interference nodes, and measurement pulses translated into luminous probability density.', glslPath:shader, tier:'free', tags:['wavefunction','probability','orbital'], semanticRole:'possibility resolving into observation', emotionalGradient:['superposition','selection'], motionToken:'motion.quantum.collapse', sourceGalleryRef:upstream, uniformsDefault:u(13,.2,.94,.92,.7,1,.68,.7,.86) },
  { id:'lorenz-field-01', family:'lorenz-field', title:'Lorenz Strange Attractor', description:'A vibrant projected flow field tracing sensitive dependence, orbit switching, and recursive return.', glslPath:shader, tier:'free', tags:['chaos','attractor','dynamics'], semanticRole:'bounded order emerging from instability', emotionalGradient:['instability','pattern'], motionToken:'motion.system.attract', sourceGalleryRef:upstream, uniformsDefault:u(14,.32,.98,.86,.88,1,.72,.94,.9) },
  { id:'reaction-diffusion-01', family:'reaction-diffusion', title:'Turing Reaction Field', description:'Animated activator-inhibitor bands resembling morphogenesis, coral growth, and chemical self-organization.', glslPath:shader, tier:'free', tags:['turing','morphogenesis','reaction-diffusion'], semanticRole:'local interaction producing global form', emotionalGradient:['reaction','organization'], motionToken:'motion.system.morph', sourceGalleryRef:upstream, uniformsDefault:u(15,.2,.92,1.08,.94,.9,.44,.62,.74) },
  { id:'phyllotaxis-01', family:'phyllotaxis', title:'Golden-Angle Phyllotaxis', description:'A living Fibonacci spiral generated at the golden angle with breathing primordia and radial growth.', glslPath:shader, tier:'free', tags:['golden-angle','fibonacci','growth'], semanticRole:'efficient packing through iterative emergence', emotionalGradient:['seed','abundance'], motionToken:'motion.nature.phyllotaxis', sourceGalleryRef:upstream, uniformsDefault:u(16,.18,.96,.82,.9,1,.62,.7,.86) },
  { id:'branch-lattice-01', family:'branch-lattice', title:'Recursive Branch Lattice', description:'A luminous bifurcation field inspired by botanical branching, recursive scaling, and relational fractions.', glslPath:shader, tier:'free', tags:['branching','recursion','tree'], semanticRole:'complexity unfolding from a compact generative rule', emotionalGradient:['root','canopy'], motionToken:'motion.nature.branch', sourceGalleryRef:upstream, uniformsDefault:u(17,.16,.94,.9,.86,.94,.66,.72,.9) }
];

export const families = ['all', ...Array.from(new Set(presets.map((preset) => preset.family)))] as const;