import type { PresetDefinition } from './types';

const upstream = 'https://github.com/MelodicBloom/shader-gallery/tree/main/abalone';
const shader = '/shaders/abalone.frag';
const fieldAtlas = '/shaders/field-atlas.frag';
const u = (family:number,speed:number,intensity:number,scale:number,structure:number,spectral:number,edge:number,flow:number,depth:number) => ({ family,speed,intensity,scale,structure,spectral,edge,flow,depth });

export const presets: PresetDefinition[] = [
  { id:'thin-film-01', family:'thin-film', title:'Thin Film Interference', description:'Layered interference membranes with drifting spectral caustics rather than flat radial bands.', glslPath:shader, tier:'free', tags:['interference','membrane','iridescence'], semanticRole:'discovery through changing perspective', emotionalGradient:['curiosity','clarity'], motionToken:'motion.discovery.refract', sourceGalleryRef:upstream, uniformsDefault:u(0,.22,.92,.94,.36,1,.76,.8,.52) },
  { id:'shell-01', family:'shell', title:'Abalone Shell', description:'Layered nacre shimmer with organic ridges, pearl depth, and migrating highlights.', glslPath:shader, tier:'free', tags:['nacre','organic','pearl'], semanticRole:'material coherence emerging from layered variation', emotionalGradient:['wonder','confidence'], motionToken:'motion.transition.bloom', sourceGalleryRef:upstream, uniformsDefault:u(1,.12,.84,1.28,.9,.78,.34,.78,.94) },
  { id:'aurora-01', family:'aurora', title:'Aurora Veil', description:'A cool-spectrum atmospheric field with flowing luminous curtains.', glslPath:shader, tier:'free', tags:['ambient','veil','atmosphere'], semanticRole:'orientation and environmental tone', emotionalGradient:['distance','invitation'], motionToken:'motion.discovery.orbit', sourceGalleryRef:upstream, uniformsDefault:u(2,.1,.76,.72,.38,.9,.2,1,.6) },
  { id:'fresnel-01', family:'fresnel', title:'Fresnel Aperture', description:'A breathing optical aperture with 3D tilt, parallax, lens depth, and a moving luminous rim.', glslPath:shader, tier:'free', tags:['aperture','parallax','reflectance'], semanticRole:'focus through boundary emphasis', emotionalGradient:['diffusion','attention'], motionToken:'motion.focus.aperture', sourceGalleryRef:upstream, uniformsDefault:u(3,.18,.94,.9,.34,.72,1,.78,1) },
  { id:'holographic-01', family:'holographic', title:'Holographic Moiré Field', description:'Layered diffraction lattices, moving moiré interference, and spectral scan currents.', glslPath:shader, tier:'free', tags:['moire','diffraction','lattice'], semanticRole:'continuity through structured variation', emotionalGradient:['fragmentation','coherence'], motionToken:'motion.structure.interfere', sourceGalleryRef:upstream, uniformsDefault:u(4,.28,.9,1.08,1,1,.58,1,.56) },
  { id:'liquid-metal-01', family:'liquid-metal', title:'Mercury Current', description:'Reflective liquid-metal folds with slow pressure-driven circulation.', glslPath:shader, tier:'free', tags:['metal','viscous','reflective'], semanticRole:'active processing and energetic transfer', emotionalGradient:['pressure','release'], motionToken:'motion.processing.current', sourceGalleryRef:upstream, uniformsDefault:u(5,.11,.88,1.06,.68,.38,.72,.94,1) },
  { id:'velvet-01', family:'velvet', title:'Velvet Chromamosh', description:'Directional velvet fibers warped by chromatic aberration, temporal morphing, and localized optical corruption.', glslPath:shader, tier:'free', tags:['fiber','chromatic-aberration','glitch'], semanticRole:'listening under unstable transmission', emotionalGradient:['quiet','distortion'], motionToken:'motion.listening.chromamosh', sourceGalleryRef:upstream, uniformsDefault:u(6,.22,.88,1.16,.92,.84,.48,.86,.8) },
  { id:'crystal-01', family:'crystal', title:'Kinetic Prismatic Crystal', description:'Rotating Voronoi facets with animated refraction, spectral seams, and crystalline parallax.', glslPath:shader, tier:'free', tags:['voronoi','refraction','prism'], semanticRole:'decision points and resolved structure', emotionalGradient:['ambiguity','resolution'], motionToken:'motion.resolve.crystallize', sourceGalleryRef:upstream, uniformsDefault:u(7,.24,.94,.94,1,.98,.82,.74,.94) },
  { id:'ion-bloom-01', family:'ion-bloom', title:'Ion Bloom', description:'Electric branching discharge with plasma bloom and luminous field collapse.', glslPath:shader, tier:'free', tags:['plasma','branching','electric'], semanticRole:'activation and energetic emergence', emotionalGradient:['charge','release'], motionToken:'motion.activate.discharge', sourceGalleryRef:upstream, uniformsDefault:u(8,.2,.98,.96,.72,1,.88,1,.74) },
  { id:'opal-glass-02', family:'opal-glass', title:'Opaline Caustic Vessel', description:'Deep translucent opal with lensing, caustic ribbons, internal bubbles, and spectral subsurface glow.', glslPath:shader, tier:'free', tags:['caustic','translucent','subsurface'], semanticRole:'soft containment and refracted depth', emotionalGradient:['opacity','revelation'], motionToken:'motion.surface.caustic', sourceGalleryRef:upstream, uniformsDefault:u(9,.15,.9,.92,.58,.92,.62,.84,1) },
  { id:'magnetic-ink-01', family:'magnetic-ink', title:'Magnetic Ink', description:'Dense pigment filaments align around a moving field; only select high-curvature strands catch a hairline spectral glint.', glslPath:shader, tier:'free', tags:['ferrofluid','field','filament'], semanticRole:'alignment under invisible influence', emotionalGradient:['scatter','orientation'], motionToken:'motion.field.align', sourceGalleryRef:upstream, uniformsDefault:u(10,.14,.92,1.02,.94,.26,.5,.82,.9) },
  { id:'electric-mesh-02', family:'electric-mesh', title:'Photonic Switching Fabric', description:'Coherent light packets route through curved waveguides, split at junctions, interfere, and recombine as an optical computing field.', glslPath:shader, tier:'free', tags:['photonics','waveguide','interference'], semanticRole:'distributed routing through constructive interference', emotionalGradient:['potential','coherence'], motionToken:'motion.network.photonic', sourceGalleryRef:upstream, uniformsDefault:u(11,.72,1,.98,.94,1,.92,1,.82) },
  { id:'quantum-knot-01', family:'quantum-knot', title:'Quantum Knot Kaleidoscope', description:'A continuously visible torus-knot filament that refracts outward and periodically tessellates across the viewport before folding home.', glslPath:shader, tier:'free', tags:['torus-knot','kaleidoscope','topology'], semanticRole:'entangled continuity expanding into repeated structure', emotionalGradient:['singularity','multiplicity'], motionToken:'motion.quantum.tessellate', sourceGalleryRef:upstream, uniformsDefault:u(12,.22,.98,.82,.88,1,.94,.92,.96) },
  { id:'wave-function-01', family:'wave-function', title:'Wave Function Collapse', description:'Complex-valued orbital lobes, interference nodes, and measurement pulses translated into luminous probability density.', glslPath:shader, tier:'free', tags:['wavefunction','probability','orbital'], semanticRole:'possibility resolving into observation', emotionalGradient:['superposition','selection'], motionToken:'motion.quantum.collapse', sourceGalleryRef:upstream, uniformsDefault:u(13,.2,.94,.92,.7,1,.68,.7,.86) },
  { id:'lorenz-field-01', family:'lorenz-field', title:'Lorenz Strange Attractor', description:'A vibrant projected flow field tracing sensitive dependence, orbit switching, and recursive return.', glslPath:shader, tier:'free', tags:['chaos','attractor','dynamics'], semanticRole:'bounded order emerging from instability', emotionalGradient:['instability','pattern'], motionToken:'motion.system.attract', sourceGalleryRef:upstream, uniformsDefault:u(14,.32,.98,.86,.88,1,.72,.94,.9) },
  { id:'reaction-diffusion-01', family:'reaction-diffusion', title:'Turing Reaction Field', description:'Animated activator-inhibitor bands resembling morphogenesis, coral growth, and chemical self-organization.', glslPath:shader, tier:'free', tags:['turing','morphogenesis','reaction-diffusion'], semanticRole:'local interaction producing global form', emotionalGradient:['reaction','organization'], motionToken:'motion.system.morph', sourceGalleryRef:upstream, uniformsDefault:u(15,.2,.92,1.08,.94,.9,.44,.62,.74) },
  { id:'phyllotaxis-01', family:'phyllotaxis', title:'Golden-Angle Phyllotaxis', description:'Sharp golden-angle primordia unfurl beyond the frame, wind inward, and breathe as a living Fibonacci field.', glslPath:shader, tier:'free', tags:['golden-angle','fibonacci','growth'], semanticRole:'efficient packing through iterative emergence', emotionalGradient:['seed','abundance'], motionToken:'motion.nature.phyllotaxis', sourceGalleryRef:upstream, uniformsDefault:u(16,.2,1,.7,.96,1,.74,.9,.9) },
  { id:'mycelial-field-01', family:'mycelial-field', title:'Mycelial Intelligence', description:'A searching nutrient network grows, forks, reroutes, and sends luminous resource pulses through living paths.', glslPath:shader, tier:'free', tags:['mycelium','search','adaptive-network'], semanticRole:'distributed intelligence finding resilient routes', emotionalGradient:['seeking','connection'], motionToken:'motion.nature.mycelial', sourceGalleryRef:upstream, uniformsDefault:u(17,.24,.98,.88,.92,.86,.78,1,.94) },
  { id:'plasma-bloom-01', family:'plasma-bloom', title:'Plasma Rosette', description:'The preserved cellular ion interpretation: recursive electric petals gather, fold, and bloom through luminous field collapse.', glslPath:shader, tier:'free', tags:['plasma','rosette','recursive'], semanticRole:'potential organizing into radiant form', emotionalGradient:['gathering','bloom'], motionToken:'motion.activate.rosette', sourceGalleryRef:upstream, uniformsDefault:u(18,.18,.98,.94,.84,1,.86,.92,.8) },

  { id:'bose-einstein-01', family:'bose-einstein', title:'Bose–Einstein Condensate', description:'A coherent ultracold matter cloud with synchronized phase rings, quantized vortices, and collective wave behavior.', glslPath:fieldAtlas, tier:'free', tags:['condensate','coherence','vortex'], semanticRole:'many particles behaving as one field', emotionalGradient:['dispersion','coherence'], motionToken:'motion.quantum.condense', sourceGalleryRef:upstream, uniformsDefault:u(0,.17,.98,.86,.78,1,.72,.72,1) },
  { id:'chladni-01', family:'chladni-resonance', title:'Chladni Resonance', description:'Vibrating nodal geometry gathers luminous particles into changing eigenmode figures.', glslPath:fieldAtlas, tier:'free', tags:['resonance','eigenmode','vibration'], semanticRole:'frequency revealing hidden structure', emotionalGradient:['noise','resonance'], motionToken:'motion.frequency.chladni', sourceGalleryRef:upstream, uniformsDefault:u(1,.2,.96,.92,.9,1,.8,.68,.76) },
  { id:'ferrofluid-01', family:'ferrofluid', title:'Ferrofluid Crown', description:'Dark magnetic liquid rises into responsive spikes with restrained spectral glints at high-curvature ridges.', glslPath:fieldAtlas, tier:'free', tags:['ferrofluid','magnetic','spikes'], semanticRole:'matter sculpted by invisible force', emotionalGradient:['liquid','alignment'], motionToken:'motion.field.ferrofluid', sourceGalleryRef:upstream, uniformsDefault:u(2,.18,.95,.96,.94,.32,.76,.86,.96) },
  { id:'standing-wave-01', family:'standing-wave', title:'Standing Wave Chamber', description:'Counter-propagating waves lock into luminous nodes, antinodes, and shifting interference membranes.', glslPath:fieldAtlas, tier:'free', tags:['standing-wave','nodes','interference'], semanticRole:'stable structure held inside opposing motion', emotionalGradient:['motion','equilibrium'], motionToken:'motion.frequency.standing', sourceGalleryRef:upstream, uniformsDefault:u(3,.24,.96,.9,.84,1,.7,.92,.82) },
  { id:'caustic-lens-01', family:'caustic-lens', title:'Caustic Lens', description:'A tilted refractive volume focuses moving light ribbons into bright caustic crossings and a breathing optical rim.', glslPath:fieldAtlas, tier:'free', tags:['caustic','lens','refraction'], semanticRole:'attention concentrated through curvature', emotionalGradient:['diffuse','focus'], motionToken:'motion.optics.caustic', sourceGalleryRef:upstream, uniformsDefault:u(4,.22,.98,.88,.7,1,.94,.82,1) },
  { id:'soap-film-01', family:'soap-film', title:'Soap Film Membrane', description:'A living interference membrane stretches, drains, and reveals thickness through spectral caustics and hairline veins.', glslPath:fieldAtlas, tier:'free', tags:['soap-film','thin-film','membrane'], semanticRole:'fragility made visible through interference', emotionalGradient:['tension','iridescence'], motionToken:'motion.surface.soapfilm', sourceGalleryRef:upstream, uniformsDefault:u(5,.19,.96,.92,.68,1,.82,.88,.72) },
  { id:'polarization-01', family:'polarization-field', title:'Polarization Field', description:'Rotating wave orientations intersect through Malus-law-inspired brightness, angular nodes, and chromatic crossings.', glslPath:fieldAtlas, tier:'free', tags:['polarization','malus-law','wave'], semanticRole:'orientation controlling transmitted intensity', emotionalGradient:['misalignment','transmission'], motionToken:'motion.optics.polarize', sourceGalleryRef:upstream, uniformsDefault:u(6,.23,.97,.9,.82,1,.78,.84,.8) },
  { id:'gravitational-lensing-01', family:'gravitational-lensing', title:'Gravitational Lensing', description:'A moving mass bends a star field into an Einstein ring while an accretion band warps across the optical horizon.', glslPath:fieldAtlas, tier:'free', tags:['gravity','einstein-ring','lensing'], semanticRole:'hidden mass inferred through distorted light', emotionalGradient:['distance','curvature'], motionToken:'motion.gravity.lens', sourceGalleryRef:upstream, uniformsDefault:u(7,.14,1,.86,.66,1,1,.64,1) },
  { id:'voronoi-growth-01', family:'voronoi-growth', title:'Voronoi Crystal Growth', description:'Moving seeds compete for space as translucent cells nucleate, expand, pulse, and resolve into crystalline boundaries.', glslPath:fieldAtlas, tier:'free', tags:['voronoi','nucleation','growth'], semanticRole:'territory emerging through nearest relationships', emotionalGradient:['seed','crystal'], motionToken:'motion.crystal.voronoi', sourceGalleryRef:upstream, uniformsDefault:u(8,.18,.96,.9,.9,1,.86,.7,.92) },
  { id:'electromagnetic-flux-01', family:'electromagnetic-flux', title:'Electromagnetic Flux', description:'Orbiting sources cast coiling flux filaments whose pulses strengthen, cancel, and reorganize across the field.', glslPath:fieldAtlas, tier:'free', tags:['electromagnetic','flux','field-lines'], semanticRole:'distributed influence around moving charge', emotionalGradient:['charge','coupling'], motionToken:'motion.field.flux', sourceGalleryRef:upstream, uniformsDefault:u(9,.28,.99,.9,.86,1,.9,1,.9) },
  { id:'curl-vorticity-01', family:'curl-vorticity', title:'Curl Noise Vorticity', description:'A divergence-light flow folds luminous filaments into vortices, eddies, and continuously advected ribbons.', glslPath:fieldAtlas, tier:'free', tags:['curl-noise','vorticity','advection'], semanticRole:'coherent motion emerging from local rotation', emotionalGradient:['drift','vortex'], motionToken:'motion.flow.vorticity', sourceGalleryRef:upstream, uniformsDefault:u(10,.3,.98,.94,.9,1,.74,1,.8) },
  { id:'flow-networks-01', family:'flow-networks', title:'Flow Networks', description:'Parallel routes bend, exchange luminous packets, and expose congestion, throughput, and coordinated transport.', glslPath:fieldAtlas, tier:'free', tags:['flow','routing','network'], semanticRole:'movement revealing system capacity', emotionalGradient:['congestion','throughput'], motionToken:'motion.network.flow', sourceGalleryRef:upstream, uniformsDefault:u(11,.42,.98,.92,.88,1,.84,1,.76) }
];

export const families = ['all', ...Array.from(new Set(presets.map((preset) => preset.family)))] as const;